### ISSUE TITLE
Using the image in the blog post

### ISSUE THREAD

**Issue by labdmitriy** [TomasBeuzen/tomasbeuzen.github.io#1]
Hi @TomasBeuzen,

I am writing the blog post about contributing to open source, and your [picture](https://github.com/TomasBeuzen/tomasbeuzen.github.io/blob/master/post/git-fork-branch-pull/featured.png) for fork & pull request git worklow is great, can I use it in my post with the reference to you and your article?

I didn't find the license for this repository so I decided to ask you.

Thank you.

**Comment by TomasBeuzen** [comment]
Hey @labdmitriy - thanks for asking and feel free to use! I just added a CC0 license :)

**Comment by labdmitriy** [comment]
Thank you!
